### ISSUE TITLE
Downstream call returns duplicates

### ISSUE THREAD

**Issue by jhsinger-klotho** [klothoplatform/klotho#895]
looks like our WalkDown function was changed in this commit https://github.com/klothoplatform/klotho/commit/3229c71be4cefa4ddb6e6d43adaf4c8a1b3aa1bd#diff-1048046ff9f8ffa2ae3375583203c3f69b1a13411c095bcb6f9e781869f07ac4

as a result im seeing many duplicates being returned when temmplates call allDownstream.

![Image](https://github.com/klothoplatform/klotho/assets/111291520/47530382-7120-4d49-b2f6-a225d7f10c18)

reproducer
```
constraints:
- operator: must_exist
  scope: edge
  target:
    source: aws:cloudfront_distribution:cloudfront_distribution_2
    target: aws:rest_api:rest_api_0
resources:
    aws:api_stage:rest_api_0:api_stage-0:
        Deployment: aws:api_deployment:rest_api_0:api_deployment-0
        RestApi: aws:rest_api:rest_api_0
        StageName: stage
    aws:cloudfront_distribution:cloudfront_distribution_2:
        DefaultCacheBehavior:
            AllowedMethods:
                - DELETE
                - GET
                - HEAD
                - OPTIONS
                - PATCH
                - POST
                - PUT
            CachedMethods:
                - HEAD
                - GET
            DefaultTtl: 3600
            ForwardedValues:
                Cookies:
                    Forward: none
                QueryString: true
            MaxTtl: 86400
            MinTtl: 0
            ViewerProtocolPolicy: allow-all
        Enabled: true
        Restrictions:
            GeoRestriction:
                RestrictionType: none
        ViewerCertificate:
            CertificateSource: cloudfront
            MinimumProtocolVersion: TLSv1
            SSLSupportMethod: sni-only
    aws:api_deployment:rest_api_0:api_deployment-0:
        RestApi: aws:rest_api:rest_api_0
        Triggers:
            rest_api_0_integration_0: rest_api_0_integration_0
            rest_api_0_integration_0_method: rest_api_0_integration_0_method
    aws:rest_api:rest_api_0:
        BinaryMediaTypes:
            - application/octet-stream
            - image/*
    aws:api_resource:rest_api_0:api_resource-0:
        FullPath: /{proxy+}
        PathPart: '{proxy+}'
        RestApi: aws:rest_api:rest_api_0
    aws:api_method:rest_api_0:rest_api_0_integration_0_method:
        Authorization: NONE
        HttpMethod: ANY
        RequestParameters:
            method.request.path.proxy: true
        Resource: aws:api_resource:rest_api_0:api_resource-0
        RestApi: aws:rest_api:rest_api_0
    aws:api_integration:rest_api_0:rest_api_0_integration_0:
        IntegrationHttpMethod: ANY
        Method: aws:api_method:rest_api_0:rest_api_0_integration_0_method
        RequestParameters:
            integration.request.path.proxy: method.request.path.proxy
        Resource: aws:api_resource:rest_api_0:api_resource-0
        RestApi: aws:rest_api:rest_api_0
        Route: /{proxy+}
edges:
    aws:api_stage:rest_api_0:api_stage-0 -> aws:api_deployment:rest_api_0:api_deployment-0:
    aws:api_stage:rest_api_0:api_stage-0 -> aws:rest_api:rest_api_0:
    aws:api_deployment:rest_api_0:api_deployment-0 -> aws:api_integration:rest_api_0:rest_api_0_integration_0:
    aws:api_deployment:rest_api_0:api_deployment-0 -> aws:api_method:rest_api_0:rest_api_0_integration_0_method:
    aws:api_deployment:rest_api_0:api_deployment-0 -> aws:rest_api:rest_api_0:
    aws:rest_api:rest_api_0 -> aws:api_integration:rest_api_0:rest_api_0_integration_0:
    aws:rest_api:rest_api_0 -> aws:api_method:rest_api_0:rest_api_0_integration_0_method:
    aws:rest_api:rest_api_0 -> aws:api_resource:rest_api_0:api_resource-0:
    aws:api_resource:rest_api_0:api_resource-0 -> aws:api_integration:rest_api_0:rest_api_0_integration_0:
    aws:api_resource:rest_api_0:api_resource-0 -> aws:api_method:rest_api_0:rest_api_0_integration_0_method:
    aws:api_method:rest_api_0:rest_api_0_integration_0_method -> aws:api_integration:rest_api_0:rest_api_0_integration_0:
```
