### ISSUE TITLE
Editing ECS container path (from the service config) doesn't save

### ISSUE THREAD

**Issue by gordon-klotho** [klothoplatform/klotho#929]
![Image](https://github.com/klothoplatform/klotho/assets/90645437/d4adedb3-7003-4f0b-be9d-e6cfb26830b1)

Seems like the constraint is passed in correctly, so this is likely an engine bug.

**Comment by gordon-klotho** [comment]
Repro input:
```yaml
constraints:
  - scope: resource
    operator: equals
    target: aws:ecs_task_definition:a
    property: ContainerDefinitions[0].Cpu
    value: 512
resources:
  aws:security_group:vpc-0:a-security_group:
    EgressRules:
      - CidrBlocks:
          - 0.0.0.0/0
        Description: Allows all outbound IPv4 traffic
        FromPort: 0
        Protocol: '-1'
        ToPort: 0
    IngressRules:
      - Description: Allow ingress traffic from within the same security group
        FromPort: 0
        Protocol: '-1'
        Self: true
        ToPort: 0
    Vpc: aws:vpc:vpc-0
  aws:ecs_service:a:
    AssignPublicIp: false
    Cluster: aws:ecs_cluster:ecs_cluster-0
    DesiredCount: 1
    ForceNewDeployment: true
    LaunchType: FARGATE
    SecurityGroups:
      - aws:security_group:vpc-0:a-security_group
    Subnets:
      - aws:subnet:vpc-0:subnet-0
      - aws:subnet:vpc-0:subnet-1
    TaskDefinition: aws:ecs_task_definition:a
  aws:ecs_cluster:ecs_cluster-0:
  aws:ecs_task_definition:a:
    ContainerDefinitions:
      - Cpu: 256
        Essential: true
        Image: aws:ecr_image:a-a
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: aws:log_group:a-log-group#LogGroupName
            awslogs-region: aws:region:region-0#Name
            awslogs-stream-prefix: a-a
        Memory: 512
        Name: a
        PortMappings:
          - ContainerPort: 80
            HostPort: 80
            Protocol: TCP
    Cpu: '256'
    ExecutionRole: aws:iam_role:a-execution-role
    Memory: '512'
    NetworkMode: awsvpc
    RequiresCompatibilities:
      - FARGATE
    TaskRole: aws:iam_role:a-execution-role
  aws:subnet:vpc-0:subnet-0:
    AvailabilityZone: aws:availability_zone:region-0:availability_zone-0
    CidrBlock: 10.0.128.0/18
    MapPublicIpOnLaunch: false
    RouteTable: aws:route_table:vpc-0:subnet-0-route_table
    Type: private
    Vpc: aws:vpc:vpc-0
  aws:subnet:vpc-0:subnet-1:
    AvailabilityZone: aws:availability_zone:region-0:availability_zone-1
    CidrBlock: 10.0.192.0/18
    MapPublicIpOnLaunch: false
    RouteTable: aws:route_table:vpc-0:subnet-1-route_table
    Type: private
    Vpc: aws:vpc:vpc-0
  aws:ecr_image:a-a:
    Context: .
    Dockerfile: a-a.Dockerfile
    Repo: aws:ecr_repo:a-a-ecr_repo
  aws:iam_role:a-execution-role:
    AssumeRolePolicyDoc:
      Statement:
        - Action:
            - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              - ecs-tasks.amazonaws.com
      Version: '2012-10-17'
    ManagedPolicies:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  aws:log_group:a-log-group:
    LogGroupName: /aws/ecs/a
    RetentionInDays: 5
  aws:route_table_association:subnet-0-subnet-0-route_table:
    RouteTable: aws:route_table:vpc-0:subnet-0-route_table
    Subnet: aws:subnet:vpc-0:subnet-0
  aws:route_table_association:subnet-1-subnet-1-route_table:
    RouteTable: aws:route_table:vpc-0:subnet-1-route_table
    Subnet: aws:subnet:vpc-0:subnet-1
  aws:ecr_repo:a-a-ecr_repo:
    ForceDelete: true
  aws:route_table:vpc-0:subnet-0-route_table:
    Routes:
      - CidrBlock: 0.0.0.0/0
        NatGateway: aws:nat_gateway:subnet-2:subnet-0-route_table-nat_gateway
    Vpc: aws:vpc:vpc-0
  aws:route_table:vpc-0:subnet-1-route_table:
    Routes:
      - CidrBlock: 0.0.0.0/0
        NatGateway: aws:nat_gateway:subnet-3:subnet-1-route_table-nat_gateway
    Vpc: aws:vpc:vpc-0
  aws:nat_gateway:subnet-2:subnet-0-route_table-nat_gateway:
    ElasticIp: aws:elastic_ip:subnet-0-route_table-nat_gateway-elastic_ip
    Subnet: aws:subnet:vpc-0:subnet-2
  aws:nat_gateway:subnet-3:subnet-1-route_table-nat_gateway:
    ElasticIp: aws:elastic_ip:subnet-1-route_table-nat_gateway-elastic_ip
    Subnet: aws:subnet:vpc-0:subnet-3
  aws:elastic_ip:subnet-0-route_table-nat_gateway-elastic_ip:
  aws:subnet:vpc-0:subnet-2:
    AvailabilityZone: aws:availability_zone:region-0:availability_zone-0
    CidrBlock: 10.0.0.0/18
    MapPublicIpOnLaunch: false
    RouteTable: aws:route_table:vpc-0:subnet-2-route_table
    Type: public
    Vpc: aws:vpc:vpc-0
  aws:elastic_ip:subnet-1-route_table-nat_gateway-elastic_ip:
  aws:subnet:vpc-0:subnet-3:
    AvailabilityZone: aws:availability_zone:region-0:availability_zone-1
    CidrBlock: 10.0.64.0/18
    MapPublicIpOnLaunch: false
    RouteTable: aws:route_table:vpc-0:subnet-3-route_table
    Type: public
    Vpc: aws:vpc:vpc-0
  aws:availability_zone:region-0:availability_zone-0:
    Index: 0
    Region: aws:region:region-0
  aws:route_table_association:subnet-2-subnet-2-route_table:
    RouteTable: aws:route_table:vpc-0:subnet-2-route_table
    Subnet: aws:subnet:vpc-0:subnet-2
  aws:availability_zone:region-0:availability_zone-1:
    Index: 1
    Region: aws:region:region-0
  aws:route_table_association:subnet-3-subnet-3-route_table:
    RouteTable: aws:route_table:vpc-0:subnet-3-route_table
    Subnet: aws:subnet:vpc-0:subnet-3
  aws:route_table:vpc-0:subnet-2-route_table:
    Routes:
      - CidrBlock: 0.0.0.0/0
        Gateway: aws:internet_gateway:vpc-0:internet_gateway-0
    Vpc: aws:vpc:vpc-0
  aws:region:region-0:
  aws:route_table:vpc-0:subnet-3-route_table:
    Routes:
      - CidrBlock: 0.0.0.0/0
        Gateway: aws:internet_gateway:vpc-0:internet_gateway-0
    Vpc: aws:vpc:vpc-0
  aws:internet_gateway:vpc-0:internet_gateway-0:
    Vpc: aws:vpc:vpc-0
  aws:vpc:vpc-0:
    CidrBlock: 10.0.0.0/16
    EnableDnsHostnames: true
    EnableDnsSupport: true
edges:
  aws:security_group:vpc-0:a-security_group -> aws:ecs_service:a:
  aws:security_group:vpc-0:a-security_group -> aws:vpc:vpc-0:
  aws:ecs_service:a -> aws:ecs_cluster:ecs_cluster-0:
  aws:ecs_service:a -> aws:ecs_task_definition:a:
  aws:ecs_service:a -> aws:subnet:vpc-0:subnet-0:
  aws:ecs_service:a -> aws:subnet:vpc-0:subnet-1:
  aws:ecs_task_definition:a -> aws:ecr_image:a-a:
  aws:ecs_task_definition:a -> aws:iam_role:a-execution-role:
  aws:ecs_task_definition:a -> aws:log_group:a-log-group:
  aws:subnet:vpc-0:subnet-0 -> aws:availability_zone:region-0:availability_zone-0:
  aws:subnet:vpc-0:subnet-0 -> aws:route_table_association:subnet-0-subnet-0-route_table:
  aws:subnet:vpc-0:subnet-0 -> aws:vpc:vpc-0:
  aws:subnet:vpc-0:subnet-1 -> aws:availability_zone:region-0:availability_zone-1:
  aws:subnet:vpc-0:subnet-1 -> aws:route_table_association:subnet-1-subnet-1-route_table:
  aws:subnet:vpc-0:subnet-1 -> aws:vpc:vpc-0:
  aws:ecr_image:a-a -> aws:ecr_repo:a-a-ecr_repo:
  aws:route_table_association:subnet-0-subnet-0-route_table -> aws:route_table:vpc-0:subnet-0-route_table:
  aws:route_table_association:subnet-1-subnet-1-route_table -> aws:route_table:vpc-0:subnet-1-route_table:
  aws:route_table:vpc-0:subnet-0-route_table -> aws:nat_gateway:subnet-2:subnet-0-route_table-nat_gateway:
  aws:route_table:vpc-0:subnet-0-route_table -> aws:vpc:vpc-0:
  aws:route_table:vpc-0:subnet-1-route_table -> aws:nat_gateway:subnet-3:subnet-1-route_table-nat_gateway:
  aws:route_table:vpc-0:subnet-1-route_table -> aws:vpc:vpc-0:
  aws:nat_gateway:subnet-2:subnet-0-route_table-nat_gateway -> aws:elastic_ip:subnet-0-route_table-nat_gateway-elastic_ip:
  aws:nat_gateway:subnet-2:subnet-0-route_table-nat_gateway -> aws:subnet:vpc-0:subnet-2:
  aws:nat_gateway:subnet-3:subnet-1-route_table-nat_gateway -> aws:elastic_ip:subnet-1-route_table-nat_gateway-elastic_ip:
  aws:nat_gateway:subnet-3:subnet-1-route_table-nat_gateway -> aws:subnet:vpc-0:subnet-3:
  aws:subnet:vpc-0:subnet-2 -> aws:availability_zone:region-0:availability_zone-0:
  aws:subnet:vpc-0:subnet-2 -> aws:route_table_association:subnet-2-subnet-2-route_table:
  aws:subnet:vpc-0:subnet-2 -> aws:vpc:vpc-0:
  aws:subnet:vpc-0:subnet-3 -> aws:availability_zone:region-0:availability_zone-1:
  aws:subnet:vpc-0:subnet-3 -> aws:route_table_association:subnet-3-subnet-3-route_table:
  aws:subnet:vpc-0:subnet-3 -> aws:vpc:vpc-0:
  aws:availability_zone:region-0:availability_zone-0 -> aws:region:region-0:
  aws:route_table_association:subnet-2-subnet-2-route_table -> aws:route_table:vpc-0:subnet-2-route_table:
  aws:availability_zone:region-0:availability_zone-1 -> aws:region:region-0:
  aws:route_table_association:subnet-3-subnet-3-route_table -> aws:route_table:vpc-0:subnet-3-route_table:
  aws:route_table:vpc-0:subnet-2-route_table -> aws:internet_gateway:vpc-0:internet_gateway-0:
  aws:route_table:vpc-0:subnet-2-route_table -> aws:vpc:vpc-0:
  aws:route_table:vpc-0:subnet-3-route_table -> aws:internet_gateway:vpc-0:internet_gateway-0:
  aws:route_table:vpc-0:subnet-3-route_table -> aws:vpc:vpc-0:
  aws:internet_gateway:vpc-0:internet_gateway-0 -> aws:vpc:vpc-0:
```
